package it.cle.project.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

@Entity
@Table(name = "users")
@XmlRootElement(name = "users")  
public class User {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  private String firstName;
	private String middleName;
	private String lastName;
	private String dob;
	private String gender;
	private String email;
	private String password;



	public long getId() {
		return this.id;
	}
	@XmlAttribute(name="id")
	public void setId(long id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}
	@XmlAttribute(name="first_name")
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}
	@XmlAttribute(name="middle_name")
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}
	@XmlAttribute(name="last_name")
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDob() {
		return this.dob;
	}
	@XmlAttribute(name="dob")
	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}
	@XmlAttribute(name="gender")
	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}
	@XmlAttribute(name="email")
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	@XmlAttribute(name="password")
	public void setPassword(String password) {
		this.password = password;
	}

	


}